general {
    lock_cmd = pidof hyprlock || hyprlock       # évite de lancer plusieurs instances
    before_sleep_cmd = loginctl lock-session     # signal de lock avant la mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on  # réactive les écrans au réveil
}

# (Optionnel) Extinction de l'écran après 5 min d'inactivité
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# (Optionnel) Lock après 10 min d'inactivité
listener {
    timeout = 600
    on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch dpms on
}
