# KITTY CONFIG FILE
# Configuration
font_family family="CaskaydiaCove Nerd Font Mono"
font_size                       11
bold_font                       auto
italic_font                     auto
bold_italic_font                auto
remember_window_size            no
initial_window_width            950
initial_window_height           500
cursor_blink_interval           0.5
cursor_stop_blinking_after      5
scrollback_lines                2000
wheel_scroll_min_lines          1
enable_audio_bell               yes
window_padding_width            10
hide_window_decorations         yes
background_opacity              0.8
dynamic_background_opacity      yes
confirm_os_window_close         0
# selection_foreground      none
# selection_background      none
tab_bar_style               powerline
tab_powerline_style         round

# Animated cursor follows text
include ~/.config/kitty/kitty-cursor-trail.conf

# Catppuccin-Mocha
include current-theme.conf