# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#cdd6f4"

# Title color for boxes
theme[title]="#cba6f7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b4befe"

# Background color of selected item in processes box
theme[selected_bg]="#cba6f7"

# Foreground color of selected item in processes box
theme[selected_fg]="#1e1e2e"

# Color of inactive/disabled text
theme[inactive_fg]="#a6adc8"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b4befe"

# Cpu box outline color
theme[cpu_box]="#6c7086"

# Memory/disks box outline color
theme[mem_box]="#6c7086"

# Net up/down box outline color
theme[net_box]="#6c7086"

# Processes box outline color
theme[proc_box]="#6c7086"

# Box divider line and small boxes line color
theme[div_line]="#1e1e2e"

# Temperature graph colors
theme[temp_start]="#b4befe"
theme[temp_mid]="#cba6f7"
theme[temp_end]="#f38ba8"

# CPU graph colors
theme[cpu_start]="#b4befe"
theme[cpu_mid]="#cba6f7"
theme[cpu_end]="#f38ba8"

# Mem/Disk free meter
theme[free_start]="#b4befe"
theme[free_mid]=""
theme[free_end]="#313244"

# Mem/Disk cached meter
theme[cached_start]="#b4befe"
theme[cached_mid]=""
theme[cached_end]="#313244"

# Mem/Disk available meter
theme[available_start]="#cba6f7"
theme[available_mid]=""
theme[available_end]="#55307f"

# Mem/Disk used meter
theme[used_start]="#f38ba8"
theme[used_mid]=""
theme[used_end]="#8c1d18"

# Download graph colors
theme[download_start]="#b4befe"
theme[download_mid]="#cba6f7"
theme[download_end]="#b4befe"

# Upload graph colors
theme[upload_start]="#b4befe"
theme[upload_mid]="#cba6f7"
theme[upload_end]="#b4befe"