#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors
env = HYPRCURSOR_SIZE,24
env = TERMINAL, kitty
