#      __ __              __             __                 ____         ____ __      
#     ╱ ╱╱ ╱_ _____  ____╱ ╱__ ____  ___╱ ╱  _______  ___  ╱ _(_)__ _   ╱ _(_) ╱__ ___
#    ╱ _  ╱ ╱╱ ╱ _ ╲╱ __╱ ╱ _ `╱ _ ╲╱ _  ╱  ╱ __╱ _ ╲╱ _ ╲╱ _╱ ╱ _ `╱  ╱ _╱ ╱ ╱ ─_│_─<
#   ╱_╱╱_╱╲_, ╱ .__╱_╱ ╱_╱╲_,_╱_╱╱_╱╲_,_╱   ╲__╱╲___╱_╱╱_╱_╱╱_╱╲_, ╱  ╱_╱╱_╱_╱╲__╱___╱
#        ╱___╱_╱                                              ╱___╱                   


# SOURCING FILES
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/rules.conf
# Replace the "fr" by "us" for qwerty keyboards
source = ~/.config/hypr/input-fr.conf
source = ~/.config/hypr/binds-fr.conf
source = ~/.config/hypr/workspaces.conf
source = ~/.config/hypr/colors.conf
